fix: missing include in windowstatethread.h
Fixes the following build failure on Arch:

```
/build/deepin-camera/src/deepin-camera-1.2.1/src/src/windowstatethread.cpp: In member function ‘virtual void windowStateThread::run()’:
/build/deepin-camera/src/deepin-camera-1.2.1/src/src/windowstatethread.cpp:45:27: error: ‘sleep_for’ is not a member of ‘std::this_thread’
   45 |         std::this_thread::sleep_for(std::chrono::seconds(1));
      |                           ^~~~~~~~~
```